FIX: Strip-off node-mongo-script from api-boilerplate template
collabo-community/backend-api-boilerplates pull request #1
Opened 2024-03-12 09:14 UTC by samuko-things

**This pull request makes the following changes**
* Fixes collabo-community/contributor-issue-report#5

**General checklist**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**
- [ ] node-mongo-script dependency has been removed totally from the ts, esm, and cjs boilerplate template
- [ ] the boilerplate templates still works as before but without the script dependency. 
- [ ] I certify that I ran my checklist

Ping @Ifycode @collabo-community/review-backend-api

2024-03-12 09:17 UTC, samuko-things commented
@Ifycode, @collabo-community/review-backend-api 
- I have removed the node-mongo-script from the ts template.
- the ts template still works as before (without the node-mongo-script)
> run ts template with `npm run dev:atlas` or `npm run dev:local`

2024-03-12 09:29 UTC, samuko-things commented
- I have removed the node-mongo-script from the **esm** template.
- the **esm** template still works as before (without the node-mongo-script)
> run **esm** template with `npm run dev:atlas` or `npm run dev:local`

2024-03-12 09:51 UTC, samuko-things commented
- I have removed the node-mongo-script from the **cjs** template.
- the **cjs** template still works as before (without the node-mongo-script)
> run **cjs** template with `npm run dev:atlas` or `npm run dev:local`

2024-03-12 10:29 UTC, Ifycode requested changes
In the `node-mongo-helpers.js` file, only retain the console.log functions: success, warning and error.
All others, you can remove them as those are for the scripts.

> All 3 templates.

2024-03-12 10:29 UTC, Ifycode commented on cjs/package.json
>    "author": "Obiagba Mary",
remove `dev:restore` and `dev:change` scripts in the 3 templates

2024-03-12 10:45 UTC, Ifycode commented on cjs/package.json
>    "author": "Obiagba Mary",
Just remove this one, leave the cancelled comment for me to handle @samuko-things

2024-03-12 21:53 UTC, Ifycode requested changes

2024-03-12 21:53 UTC, Ifycode commented on cjs/package.json
>    "author": "Obiagba Mary",
@samuko-things 
1. remove `dev:restore` and `dev:change` scripts in the 3 templates

2024-03-12 21:53 UTC, Ifycode commented on esm/node-mongo-helpers.js
2. I have fixed some things in the esm template and I've merged it into this PR.
The changes I made:
- There is now only one `.server` file, and one `.connect` file (the name of the files change accordingly, and I also updated their content accordingly)
- I merged some functions together in the process to achieve this (and the names of the functions change accordingly)
- Added new piece of code in the `node-mongo-helpers.js` to check which connection type the user chose based on which npm dev script they are running, and apply .env settings accordingly.
- Adjusted package.json to single server.js file

Referencing my PR: https://github.com/collabo-community/backend-api-boilerplates/pull/2/files

You are to help to do this exact same thing in the ts and cjs templates @samuko-things

2024-03-13 08:32 UTC, samuko-things commented on cjs/package.json
>    "author": "Obiagba Mary",
Ok, I understand @Ifycode

2024-03-13 08:43 UTC, samuko-things commented
I have just removed the `dev:change` and `dev:restore` scripts from the 3 templates

2024-03-13 08:44 UTC, samuko-things commented on cjs/package.json
>    "author": "Obiagba Mary",
> @samuko-things
> 
> 1. remove `dev:restore` and `dev:change` scripts in the 3 templates

I have just removed the `dev:change` and `dev:restore` scripts from the 3 templates

2024-03-13 11:01 UTC, samuko-things commented on esm/node-mongo-helpers.js
> 2. I have fixed some things in the esm template and I've merged it into this PR.
>    The changes I made:
> 
> * There is now only one `.server` file, and one `.connect` file (the name of the files change accordingly, and I also updated their content accordingly)
> * I merged some functions together in the process to achieve this (and the names of the functions change accordingly)
> * Added new piece of code in the `node-mongo-helpers.js` to check which connection type the user chose based on which npm dev script they are running, and apply .env settings accordingly.
> * Adjusted package.json to single server.js file
> 
> Referencing my PR: https://github.com/collabo-community/backend-api-boilerplates/pull/2/files
> 
> You are to help to do this exact same thing in the ts and cjs templates @samuko-things

I have made the necessary changes to the ts and cjs template. I have also tested it and it all works.

2024-03-13 16:35 UTC, Ifycode requested changes

2024-03-13 16:35 UTC, Ifycode commented on cjs/.env.example
> +PORT_LOCAL=8081
`PORT_ATLAS` & `PORT_LOCAL` values in the env.json file I see you changed it in the cjs template. If you change it here, you have to also change the ts template too.

2024-03-13 16:35 UTC, Ifycode commented on cjs/node-mongo-helpers.js
> +  success('\nConnected to mongoDB');
Add a check for this success string: 
`'\nConnected to [local] mongoDB [Atlas]'`
Where local text shows up only if user is running local, and atlas shows up only if user is running atlas.

2024-03-15 00:03 UTC, Ifycode commented on cjs/node-mongo-helpers.js
> +  success('\nConnected to mongoDB');
@samuko-things see what I changed `esm` template here, I've merged it in this your PR.
https://github.com/collabo-community/backend-api-boilerplates/pull/3/files

> Use the same for `ts` and `cjs` too

2024-03-15 09:42 UTC, samuko-things commented on cjs/node-mongo-helpers.js
> +  success('\nConnected to mongoDB');
@Ifycode, I've made the changes and updated the cjs and ts file as requested.

2024-03-15 14:46 UTC, Ifycode approved these changes

2024-03-15 14:47 UTC, merged