Added js-cjs-async-await template
collabo-community/backend-api-boilerplates pull request #11
Opened 2024-05-03 12:38 UTC by Danbaba1

**This pull request makes the following changes**
* Fixes collabo-community/contributor-issue-report#8 

**General checklist**
- [x] File or folder now contains changes as specified in the issue I worked on
- [x] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**

Replace this text with the testing checklist from the issue this pull request fixes.

Ping @code-collabo/node-mongo-api-boilerplate-templates

2024-05-03 12:44 UTC, Danbaba1 commented
The P.R. is ready @collabo-community/review-backend-api

2024-05-09 13:57 UTC, Danbaba1 commented
The P.R is ready for review @collabo-community/review-backend-api

2024-05-13 09:39 UTC, samuko-things commented
@Danbaba1 are all endpoints now working?

2024-05-13 10:34 UTC, samuko-things requested changes

2024-05-13 10:34 UTC, samuko-things commented on js-cjs-async-await/package.json
> +  "description": "Javascript (Common js import/export syntax and .then() asynchronous code handing method) Backend API boilerplate template generated via Collabo Community's create-collabo-app projec
Change the `"name"` to `"js-cjs-async-await-backend-api-boilerplate"`.
Change the `"description"` to `"Javascript (Common js import/export syntax and async-await asynchronous code handing method) Backend API boilerplate template generated via Collabo Community's create-collabo-app project"`

2024-05-13 10:34 UTC, samuko-things commented on js-cjs-async-await/src/api/services/demo.service.js
> +};
don't export the service functions this way. rather make use of the `module.exports` you commented below. let all the functions be `const functionName = async () ....`

2024-05-13 10:37 UTC, Danbaba1 commented on js-cjs-async-await/src/api/services/demo.service.js
> +};
It was giving errors that way that was why I used this method sir

2024-05-13 10:38 UTC, Danbaba1 commented on js-cjs-async-await/package.json
> +  "description": "Javascript (Common js import/export syntax and .then() asynchronous code handing method) Backend API boilerplate template generated via Collabo Community's create-collabo-app projec
Okay sir

2024-05-14 08:23 UTC, Danbaba1 commented on js-cjs-async-await/src/api/services/demo.service.js
> +};
I have made the changes you requested via the review on Github and tested the endpoints. They are all working.

2024-05-14 08:57 UTC, samuko-things requested changes

2024-05-14 08:57 UTC, samuko-things commented on js-cjs-async-await/src/api/controllers/demo.controller.js
> +};
You notice that this `delete...` function still uses `.then()`, please change it

2024-05-14 08:57 UTC, samuko-things commented on js-cjs-async-await/src/api/controllers/demo.controller.js
> +const getDemoItemsController = async (req, res) => {
Good job. So now for uniformity throughout the template, please change all the arrow functions to the normal function type. Since the issue is not about using the arrow function or not but basically removing `.then()` and changing it to `async await`.

For example change the above function from `const getDemoItemsController = async (req, res) => {` to `const getDemoItemsController = async functiono(req, res) {`

You can also check the `db connect` file to understand better.
Do this for all the controllers.

2024-05-14 08:57 UTC, samuko-things commented on js-cjs-async-await/src/api/services/demo.service.js
> +const getDemoItemsService = async () => {
Good job. So now for uniformity throughout the template, please change all the arrow functions to the normal function type. Since the issue is not about using the arrow function or not but basically removing `.then()` and changing it to `async await`.

For example change the above function from `const getDemoItemsService = async () => {` to `const const getDemoItemsService = async function(){`

You can also check the `db connect` file to understand better.
Do this for all the services.

2024-05-14 10:16 UTC, Danbaba1 commented on js-cjs-async-await/src/api/controllers/demo.controller.js
> +const getDemoItemsController = async (req, res) => {
I have made the changes as requested and also tested the endpoints and they are all working.

2024-05-14 15:21 UTC, samuko-things commented on js-cjs-async-await/src/api/services/demo.service.js
> +const getDemoItemsService = async () => {
@Danbaba1, you have not done that of the service file yet

2024-05-14 15:22 UTC, samuko-things commented
@Danbaba1, you have not updated the

2024-05-17 07:01 UTC, Danbaba1 commented on js-cjs-async-await/src/api/controllers/demo.controller.js
> +};
I have made the changes requested.

2024-05-17 07:02 UTC, Danbaba1 commented on js-cjs-async-await/src/api/services/demo.service.js
> +const getDemoItemsService = async () => {
I have worked on the service file.

2024-05-17 12:33 UTC, samuko-things commented
@Danbaba1, please remove the `.vscode` folder from the template.

2024-05-22 11:24 UTC, samuko-things approved these changes
I'm okay with the template code

2024-05-22 11:28 UTC, samuko-things commented
@collabo-community/review-cli, @Ifycode, @Festusali, @tylerjusfly.

I'm okay with the changes, Please help take a look so it can be merged as necessary.

2024-06-20 07:59 UTC, merged

2024-07-12 03:13 UTC, Ifycode commented
@all-contributors add @Danbaba1 for code