Fix: Add User Authentication (`local`, `jwt`, `google` Oauth2, and `github` Oauth2) to the `ts-esm-async-await` backend-api-boilerplates template using passportJs
collabo-community/backend-api-boilerplates pull request #18
Opened 2024-08-14 17:10 UTC by samuko-things

#### This pull request makes the following changes

* Fixes collabo-community/issue-tickets-ready-for-fixing#10

#

#### General checklist

- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

Replace this dummy text with the testing checklist from the issue this pull request fixes (use checkboxes similar to how it's done in the **General checklist** above).

#

#### How to run project

> [!IMPORTANT]  
> Did something change in this PR about how to run the project locally? If so, remove this alert notice (along with the tip) and follow the direction below. 

> [!TIP]  
> If this PR did not change how the project is run locally, you can just remove this how to run project section totally.

Replace this dummy text with new information on how to run the project (preferably using a list e.g. unordered list or ordered list).

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note or section. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

2024-08-16 17:09 UTC, Ifycode requested changes

2024-08-16 17:09 UTC, Ifycode commented on ts-esm-async-await/src/api/middlewares/auth.middleware.ts
> +import { unAuthorizedErr } from '../../lib/errors/Errors';
Move this file/folder and passport auth to a new auth folder that you create.

2024-08-16 19:15 UTC, samuko-things commented on ts-esm-async-await/src/api/middlewares/auth.middleware.ts
> +import { unAuthorizedErr } from '../../lib/errors/Errors';
> Move this file/folder and passport auth to a new auth folder that you create.

I have made the changes. it is now ready to be reviewed.

2024-08-17 04:36 UTC, Ifycode requested changes

2024-08-17 04:36 UTC, Ifycode commented on ts-esm-async-await/package.json
> +  "contributors": [
@samuko-things just noticing that this line about the contributors array changed in the package.json, and its not supposed to change. Please restore this line so that it doesn't show up as what changed in the files changed.

2024-08-17 04:38 UTC, Ifycode commented on ts-esm-async-await/package.json
> +  "contributors": [
Also you are not supposed to remove the note at the end of the PR's description. It was plainly written there @samuko-things

2024-08-17 10:53 UTC, Ifycode commented on ts-esm-async-await/package.json
> +  "contributors": [
Also I've updated the issue ticket, please update the testing checklist @samuko-things

2024-08-20 12:33 UTC, samuko-things commented on ts-esm-async-await/package.json
> +  "contributors": [
> Also I've updated the issue ticket @samuko-things. Please update the following in this PR based on that update:
> 
> * PR title
> * Testing checklist
> 
> Check the original pull request template to see how testing checklist should be added.

I have updated the **PR title** and the **Testing Checklist** as requested @Ifycode

2024-08-20 12:34 UTC, samuko-things commented on ts-esm-async-await/package.json
> +  "contributors": [
> Also you are not supposed to remove the note at the end of the PR's description. It was plainly written there @samuko-things
> 
> Check the original pull request template and restore accordingly.

I have added back the note @Ifycode

2024-08-20 12:40 UTC, samuko-things commented on ts-esm-async-await/package.json
> +  "contributors": [
> @samuko-things just noticing that this line about the contributors array changed in the package.json, and its not supposed to change. Please restore this line so that it doesn't show up as what changed in the files changed.

i have restored it @Ifycode

2024-08-20 12:41 UTC, samuko-things commented
I have made all necessary changes @Ifycode, it is ready for review.

2024-08-21 17:49 UTC, Ifycode approved these changes
Nice, thank you @samuko-things

2024-08-21 17:50 UTC, merged