Fix: Add Admin user to Typescript backend boilerplate template
collabo-community/backend-api-boilerplates pull request #22
Opened 2024-09-03 14:39 UTC by samuko-things

#### This pull request makes the following changes

* Fixes collabo-community/issue-tickets-ready-for-fixing#16

#

#### General checklist
- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

Replace this dummy text with the testing checklist from the issue this pull request fixes (use checkboxes similar to how it's done in the **General checklist** above).

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note or section. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

2024-09-03 18:50 UTC, samuko-things commented
@collabo-community/review-backend-api, my PR has been tested and is ready for review.

2024-09-03 20:04 UTC, Ifycode requested changes

2024-09-03 20:04 UTC, Ifycode commented on ts-esm-async-await/src/api/controllers/user.controller.ts
> +      error(`No Admin User on Your User Document (or Table).\nRestart Server to Create One\n`);
Do we need this check here in the controller or in the service file? @samuko-things 
I think it's just better to ensure that a user is created if an error is returned, instead of returning the error.
Or am I missing the context here?

2024-09-04 11:22 UTC, samuko-things commented on ts-esm-async-await/src/api/controllers/user.controller.ts
> +      error(`No Admin User on Your User Document (or Table).\nRestart Server to Create One\n`);
> Do we need this check here in the controller or in the service file? @samuko-things I think it's just better to ensure that a user is created if an error is returned, instead of returning the error. Or am I missing the context here?

I have updated the **createAdminUserControllerFunction** not to have the check. it ensures the admin user would always be created if it is not in the database.
Although I still left the error catching so as to catch any other unexpected server errors during finding or creating the admin user.

2024-09-05 10:43 UTC, samuko-things commented
@collabo-community/review-building-blocks [@Ifycode], I have made the changes to the controller file as discussed in the meeting yesterday.

2024-09-05 11:54 UTC, Ifycode approved these changes

2024-09-05 11:54 UTC, merged