Fix: [create-collabo-app] Migrate/Add Email and Password Authentication (only) - for ts-esm-async-await template only
collabo-community/backend-api-boilerplates pull request #7
Opened 2024-04-04 15:45 UTC by samuko-things

**This pull request makes the following changes**
* Fixes collabo-community/contributor-issue-report#9

**General checklist**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**
- [x] email and password authentication has been added to the ts template only (in the new boilerplate template repo).
- [x] new user model is added as seen done in the [my-todo-app](https://github.com/samuko-things-collabo-study/my-todo-app).
- [x] The other boilerplate templates still work as before untouched.
- [x] I certify that I ran my checklist

**Others can follow the steps below To Test The New Auth Code**
- pull the new `email-auth-ts` branch
- cd in the `ts-esm-async-await` template folder
- run `npm install` to download the new added package dependencies
- start the server with `npm run dev:atlas` or `npm run dev:local`
- follow the API endpoint summary below to test.
  > NOTE: Implementation can be found on the **`Collabo Postman Workspace`**
  
Ping @collabo-community/review-backend-api

2024-04-04 15:47 UTC, samuko-things commented
@collabo-community/review-backend-api and @Ifycode.
I have just added the email and password authentication and authorization.
I have also created a new collection - `User Auth CRUD` in our postman workspace for testing.

Please do check It out.

2024-04-10 11:48 UTC, samuko-things commented
@collabo-community/review-backend-api.
I have updated the readme to show a quick overview of how to test the auth part.
I have also created and set up a postman collection for it - `User Auth CRUD` in the `Collabo Community Postman Workspace` for easy testing.

2024-04-10 12:22 UTC, Ifycode requested changes

2024-04-10 12:22 UTC, Ifycode commented on README.md
> +Collabo Backend Api Boilerplates
Readme file should not be showing up in your file changes @samuko-things 

> Also wondering why the PR says there's conflict with your readme file

2024-06-28 10:04 UTC, closed without merging